namespace: demo
image:
  pullPolicy: IfNotPresent
  name: spring-template-demo
  tag: latest
resources:
  limits:
    cpu: 1000m
    memory: 500Mi
  requests:
    cpu: 500m
    memory: 500Mi
service:
  enabled: enabled
  externalPort: 8080
  internalPort: 8080
  name: spring-template-demo
  type: ClusterIP
data:
  spring.profiles.active: local
  kafka.bootstrap_servers: host.docker.internal:19093,host.docker.internal:29093,host.docker.internal:39093
  kafka.schema_registry_servers: http://host.docker.internal:8081